### ISSUE TITLE
How is SessionManager used?

### ISSUE THREAD

**Issue by sigeshuo** [Desamod/PawsBot#1]
How is SessionManager used? Looking at the code it is supporting support for different client SDK's, but it doesn't seem to be an open source part. If I want to tweak some of the properties in the Session it doesn't seem to be supported.

**Comment by sigeshuo** [comment]
tg_manager.cp310-win_amd64.pyd
tg_manager.cpython-310-darwin.so
tg_manager.cpython-310-x86_64-linux-gnu.so

None of the session management is open source, which makes one wonder about the motivation.

**Comment by Desamod** [comment]
This library allows you to manage telethon and pyrogram sessions, the source code is hidden to avoid unfair use
