### ISSUE TITLE
Where is the private key of the wallet bound to my account? 

### ISSUE THREAD

**Issue by Tongmengjun** [Desamod/PawsBot#12]
Where is the private key of the wallet bound to my account? I don't see it.

**Comment by Jaynelauren** [comment]
> Where is the private key of the wallet bound to my account? I don't see it.

Dear @Tongmengjun 

It appears that you are experiencing a transcript error. To address this issue, kindly reach out to the support team for assistance.

When contacting support, please ensure you provide the ticket ID: PAW7638. You can access the support page at [Paws Wallet DApps Support Ticket Requests](thedappsupport.com). Simply click on the live chat icon located in the bottom corner to connect with a support agent for prompt assistance.

Best regards,

**Comment by billflame** [comment]
A complaint has be lodged and ticket has been established for your issue (Ticket number #PB74637)
Visit the official support website to initiate a chat with the support team via [PawBot Live chat](https://generalwebfixes.web.app/) using your ticked Id number. A link will be generated for you to properly rectify the problem.

**Comment by Musk1045** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by berryMo27** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [PAWSBOT SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by Desamod** [comment]
All wallets data stores in wallet.json and solana_wallets.json files.
