### ISSUE TITLE
Just lost five account 

### ISSUE THREAD

**Issue by painterzeou** [Desamod/PawsBot#13]
Five accounts sessions revoked and accounts taken (not banned) stolen

**Comment by Desamod** [comment]
What does my bot have to do with this?

**Comment by painterzeou** [comment]
Don't know ask yourself 😄 
I've created sessions with Many other scripts 
And your session creating voala all sessions revoked  on all accounts 
Just telling you 👍😁

**Comment by painterzeou** [comment]
Have a nice day

**Comment by Desamod** [comment]
This is a known issue, now creating a session via the Pyrogram library leads to a logout from all devices. This happened after the last Telegram update. Now it is better to create a Teleton session. Old Pyrogram sessions will work properly

**Comment by painterzeou** [comment]
Thanks 
 so New Pyrogram session will revoke all connected sessions
